# Site settings
title: Writing
description: "In which the Ackernaut exercises his hand as a wordsmith"
url:              http://writing.ackernaut.com
permalink:        pretty
twitter_username: ackernaut
github_username:  ackernaut

# Build settings
markdown: kramdown
exclude:  [node_modules]
