# Site settings
title: Writing
email: ackernaut@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Ackernaut writes on many topics: design, code, typography, product, brand, methodology
url:              http://writing.ackernaut.com
permalink:        pretty
twitter_username: ackernaut
github_username:  ackernaut

# Build settings
markdown: kramdown
exclude:  [node_modules]
